# Generated by Django 6.0.2 on 2026-02-17 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0009_usuario_password_policy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='failed_lockouts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_lockout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='force_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='rol_objetivo',
            field=models.CharField(blank=True, choices=[('superadmin', 'Superadmin'), ('admin_sede', 'Admin de sede'), ('admin', 'Admin'), ('guarda', 'Guarda'), ('aprendiz', 'Aprendiz')], help_text='Si es null, aplica a todos los roles (si user también es null, es global).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='channel',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin_sede', 'Admin de sede'), ('admin', 'Admin'), ('guarda', 'Guarda'), ('aprendiz', 'Aprendiz')], default='aprendiz', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('salt', models.CharField(max_length=64)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'new_email', 'expires_at'], name='accesos_ema_user_id_83e387_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=512, unique=True)),
                ('public_key', models.TextField(blank=True, default='')),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, null=True)),
                ('aaguid', models.CharField(blank=True, default='', max_length=64)),
                ('nickname', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accesos_web_user_id_7e5b2d_idx')],
            },
        ),
    ]
