# Generated by Codex on 2026-02-18

from django.db import migrations, models
from django.db.models import Q


def migrate_admin_role_forward(apps, schema_editor):
    Usuario = apps.get_model("accesos", "Usuario")
    Notificacion = apps.get_model("accesos", "Notificacion")

    # Legacy admin without sede gets elevated to superadmin to avoid orphan permission scope.
    legacy_no_sede = Usuario.objects.filter(rol="admin").filter(Q(sede_principal__isnull=True) | Q(sede_principal=""))
    legacy_no_sede.update(rol="superadmin", is_staff=True, is_superuser=True)

    # Legacy admin with sede is migrated to admin_sede.
    Usuario.objects.filter(rol="admin").update(rol="admin_sede")

    # Normalize old notification target role.
    Notificacion.objects.filter(rol_objetivo="admin").update(rol_objetivo="admin_sede")


class Migration(migrations.Migration):

    dependencies = [
        ("accesos", "0010_usuario_failed_lockouts_count_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_admin_role_forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notificacion",
            name="rol_objetivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin_sede", "Admin de sede"),
                    ("guarda", "Guarda"),
                    ("aprendiz", "Aprendiz"),
                ],
                help_text="Si es null, aplica a todos los roles (si user también es null, es global).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin_sede", "Admin de sede"),
                    ("guarda", "Guarda"),
                    ("aprendiz", "Aprendiz"),
                ],
                default="aprendiz",
                max_length=20,
            ),
        ),
    ]
