# Generated by Django 6.0.2 on 2026-02-19 19:40

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


LEGACY_TO_GENERIC = {
    "CEGAFE": "sede-1",
    "SANTA_CLARA": "sede-2",
    "ITEDRIS": "sede-3",
    "GASTRONOMIA": "sede-4",
}


def _normalize_legacy(value: str) -> str:
    return str(value or "").strip().upper().replace("-", "_").replace(" ", "_")


def _to_code(value: str) -> str:
    raw = str(value or "").strip()
    if not raw:
        return ""
    normalized = _normalize_legacy(raw)
    if normalized in LEGACY_TO_GENERIC:
        return LEGACY_TO_GENERIC[normalized]
    if raw.lower().startswith("sede-"):
        return raw.lower()
    slug = slugify(raw)
    return slug[:40] if slug else ""


def _default_sedes():
    return [
        ("sede-1", "Sede 1"),
        ("sede-2", "Sede 2"),
        ("sede-3", "Sede 3"),
        ("sede-4", "Sede 4"),
    ]


def forwards_func(apps, schema_editor):
    Sede = apps.get_model("accesos", "Sede")
    Usuario = apps.get_model("accesos", "Usuario")
    Turno = apps.get_model("accesos", "Turno")
    Acceso = apps.get_model("accesos", "Acceso")

    sedes_by_code = {}
    for code, name in _default_sedes():
        sede, _ = Sede.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "is_active": True,
            },
        )
        sedes_by_code[code] = sede

    def get_or_create_sede(raw_value: str):
        code = _to_code(raw_value)
        if not code:
            return None
        existing = sedes_by_code.get(code)
        if existing:
            return existing
        sede = Sede.objects.filter(code=code).first()
        if sede:
            sedes_by_code[code] = sede
            return sede
        name = str(raw_value or "").strip().replace("_", " ")
        if not name:
            name = code.replace("-", " ").title()
        sede = Sede.objects.create(code=code, name=name[:120], is_active=True)
        sedes_by_code[code] = sede
        return sede

    fallback = sedes_by_code["sede-1"]

    for user in Usuario.objects.all().iterator():
        sede = get_or_create_sede(getattr(user, "sede_principal", None))
        user.sede_principal_fk_id = getattr(sede, "id", None)
        user.save(update_fields=["sede_principal_fk"])

    for turno in Turno.objects.all().iterator():
        sede = get_or_create_sede(getattr(turno, "sede", None)) or fallback
        turno.sede_fk_id = sede.id
        turno.save(update_fields=["sede_fk"])

    turnos_by_id = dict(Turno.objects.all().values_list("id", "sede_fk_id"))
    for acceso in Acceso.objects.all().iterator():
        sede = get_or_create_sede(getattr(acceso, "sede", None))
        if not sede and getattr(acceso, "turno_id", None):
            sede_fk_id = turnos_by_id.get(acceso.turno_id)
            if sede_fk_id:
                acceso.sede_fk_id = sede_fk_id
                acceso.save(update_fields=["sede_fk"])
                continue
        acceso.sede_fk_id = getattr(sede, "id", None)
        acceso.save(update_fields=["sede_fk"])


def backwards_func(apps, schema_editor):
    Usuario = apps.get_model("accesos", "Usuario")
    Turno = apps.get_model("accesos", "Turno")
    Acceso = apps.get_model("accesos", "Acceso")

    def to_legacy(code: str) -> str:
        raw = str(code or "").strip().upper().replace("-", "_")
        for legacy, generic in LEGACY_TO_GENERIC.items():
            if generic.upper().replace("-", "_") == raw:
                return legacy
        return raw

    for user in Usuario.objects.select_related("sede_principal_fk").all().iterator():
        code = getattr(getattr(user, "sede_principal_fk", None), "code", None)
        user.sede_principal = to_legacy(code) if code else None
        user.save(update_fields=["sede_principal"])

    for turno in Turno.objects.select_related("sede_fk").all().iterator():
        code = getattr(getattr(turno, "sede_fk", None), "code", None)
        turno.sede = to_legacy(code) if code else "CEGAFE"
        turno.save(update_fields=["sede"])

    for acceso in Acceso.objects.select_related("sede_fk").all().iterator():
        code = getattr(getattr(acceso, "sede_fk", None), "code", None)
        acceso.sede = to_legacy(code) if code else None
        acceso.save(update_fields=["sede"])


class Migration(migrations.Migration):
    dependencies = [
        ("accesos", "0011_remove_admin_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="sede_principal_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accesos.sede",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="sede_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accesos.sede",
            ),
        ),
        migrations.AddField(
            model_name="acceso",
            name="sede_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accesos.sede",
            ),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name="usuario",
            name="sede_principal",
        ),
        migrations.RemoveField(
            model_name="turno",
            name="sede",
        ),
        migrations.RemoveField(
            model_name="acceso",
            name="sede",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="sede_principal_fk",
            new_name="sede_principal",
        ),
        migrations.RenameField(
            model_name="turno",
            old_name="sede_fk",
            new_name="sede",
        ),
        migrations.RenameField(
            model_name="acceso",
            old_name="sede_fk",
            new_name="sede",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="sede_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="accesos.sede",
            ),
        ),
        migrations.AlterField(
            model_name="turno",
            name="sede",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="turnos", to="accesos.sede"),
        ),
        migrations.AlterField(
            model_name="acceso",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accesos",
                to="accesos.sede",
            ),
        ),
    ]
