# Generated by Django 6.0.2 on 2026-02-20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesos", "0012_sede_alter_acceso_sede_alter_turno_sede_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=128)),
                ("refresh_token_hash", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_sessions",
                        to="accesos.usuario",
                    ),
                ),
                (
                    "replaced_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="accesos.refreshsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["user", "device_id"], name="accesos_ref_user_id_a0dd20_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["user", "expires_at"], name="accesos_ref_user_id_fc0e81_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["device_id", "expires_at"], name="accesos_ref_device__da5a61_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["revoked_at"], name="accesos_ref_revoked_534ca3_idx"),
        ),
    ]
