# Generated by Codex on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


ROLE_SEED = [
    ("superadmin", "Superadmin"),
    ("admin_sede", "Admin de sede"),
    ("guarda", "Guarda"),
    ("aprendiz", "Aprendiz"),
]

PERMISSION_SEED = [
    ("sede.read", "Ver sedes"),
    ("sede.manage", "Gestionar sedes"),
    ("user.read", "Ver usuarios"),
    ("user.create", "Crear usuarios"),
    ("user.update", "Editar usuarios"),
    ("user.delete", "Eliminar usuarios"),
    ("membership.manage", "Gestionar membresias"),
    ("equipo.read", "Ver equipos"),
    ("equipo.create", "Crear equipos"),
    ("equipo.update", "Editar equipos"),
    ("equipo.delete", "Eliminar equipos"),
    ("equipo.review", "Revisar equipos"),
    ("turno.read", "Ver turnos"),
    ("turno.start", "Iniciar turno"),
    ("turno.resume", "Reanudar turno"),
    ("turno.end", "Finalizar turno"),
    ("turno.admin_end", "Finalizar turno administrativo"),
    ("acceso.read", "Ver accesos"),
    ("acceso.create", "Crear accesos"),
    ("acceso.scan", "Escanear documento/QR"),
    ("acceso.stats", "Ver estadisticas de accesos"),
    ("notificacion.read", "Ver notificaciones"),
    ("notificacion.write", "Gestionar notificaciones"),
    ("profile.read", "Ver perfil propio"),
    ("profile.update", "Actualizar perfil propio"),
    ("profile.email_change", "Cambiar correo con OTP"),
    ("qr.read", "Ver QR propio"),
    ("domain.manage", "Gestionar dominios permitidos"),
    ("policy.manage", "Gestionar politicas de sede"),
]

ROLE_PERMISSION_MATRIX = {
    "superadmin": [
        ("sede.read", "GLOBAL"),
        ("sede.manage", "GLOBAL"),
        ("user.read", "GLOBAL"),
        ("user.create", "GLOBAL"),
        ("user.update", "GLOBAL"),
        ("user.delete", "GLOBAL"),
        ("membership.manage", "GLOBAL"),
        ("equipo.read", "GLOBAL"),
        ("equipo.create", "GLOBAL"),
        ("equipo.update", "GLOBAL"),
        ("equipo.delete", "GLOBAL"),
        ("equipo.review", "GLOBAL"),
        ("turno.read", "GLOBAL"),
        ("turno.start", "GLOBAL"),
        ("turno.resume", "GLOBAL"),
        ("turno.end", "GLOBAL"),
        ("turno.admin_end", "GLOBAL"),
        ("acceso.read", "GLOBAL"),
        ("acceso.create", "GLOBAL"),
        ("acceso.scan", "GLOBAL"),
        ("acceso.stats", "GLOBAL"),
        ("notificacion.read", "GLOBAL"),
        ("notificacion.write", "GLOBAL"),
        ("profile.read", "GLOBAL"),
        ("profile.update", "GLOBAL"),
        ("profile.email_change", "GLOBAL"),
        ("qr.read", "GLOBAL"),
        ("domain.manage", "GLOBAL"),
        ("policy.manage", "GLOBAL"),
    ],
    "admin_sede": [
        ("sede.read", "SEDE"),
        ("user.read", "SEDE"),
        ("user.create", "SEDE"),
        ("user.update", "SEDE"),
        ("user.delete", "SEDE"),
        ("equipo.read", "SEDE"),
        ("equipo.create", "SEDE"),
        ("equipo.update", "SEDE"),
        ("equipo.delete", "SEDE"),
        ("equipo.review", "SEDE"),
        ("turno.read", "SEDE"),
        ("turno.start", "SEDE"),
        ("turno.resume", "SEDE"),
        ("turno.end", "SEDE"),
        ("turno.admin_end", "SEDE"),
        ("acceso.read", "SEDE"),
        ("acceso.create", "SEDE"),
        ("acceso.scan", "SEDE"),
        ("acceso.stats", "SEDE"),
        ("notificacion.read", "SEDE"),
        ("notificacion.write", "SEDE"),
        ("domain.manage", "SEDE"),
        ("policy.manage", "SEDE"),
    ],
    "guarda": [
        ("turno.read", "SEDE"),
        ("turno.start", "SEDE"),
        ("turno.resume", "SEDE"),
        ("turno.end", "SEDE"),
        ("acceso.read", "SEDE"),
        ("acceso.create", "SEDE"),
        ("acceso.scan", "SEDE"),
        ("acceso.stats", "SEDE"),
        ("equipo.read", "SEDE"),
        ("notificacion.read", "OWN"),
        ("profile.read", "OWN"),
        ("profile.update", "OWN"),
    ],
    "aprendiz": [
        ("profile.read", "OWN"),
        ("profile.update", "OWN"),
        ("profile.email_change", "OWN"),
        ("qr.read", "OWN"),
        ("equipo.read", "OWN"),
        ("equipo.create", "OWN"),
        ("equipo.update", "OWN"),
        ("equipo.delete", "OWN"),
        ("acceso.read", "OWN"),
        ("notificacion.read", "OWN"),
    ],
}


def _extract_domain(email: str) -> str:
    raw = str(email or "").strip().lower()
    if "@" not in raw:
        return ""
    return raw.split("@")[-1].replace("@", "")


def seed_rbac_data(apps, schema_editor):
    Sede = apps.get_model("accesos", "Sede")
    Usuario = apps.get_model("accesos", "Usuario")
    Role = apps.get_model("accesos", "Role")
    Permission = apps.get_model("accesos", "Permission")
    RolePermission = apps.get_model("accesos", "RolePermission")
    UserMembership = apps.get_model("accesos", "UserMembership")
    SedePolicy = apps.get_model("accesos", "SedePolicy")
    AllowedEmailDomain = apps.get_model("accesos", "AllowedEmailDomain")

    roles = {}
    for code, name in ROLE_SEED:
        role_obj, _ = Role.objects.get_or_create(
            code=code,
            defaults={"name": name, "is_system": True},
        )
        roles[code] = role_obj

    permissions = {}
    for code, name in PERMISSION_SEED:
        perm_obj, _ = Permission.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": ""},
        )
        permissions[code] = perm_obj

    for role_code, assignment_rows in ROLE_PERMISSION_MATRIX.items():
        role_obj = roles.get(role_code)
        if not role_obj:
            continue
        for perm_code, scope in assignment_rows:
            perm_obj = permissions.get(perm_code)
            if not perm_obj:
                continue
            RolePermission.objects.get_or_create(
                role=role_obj,
                permission=perm_obj,
                scope=scope,
            )

    sedes = list(Sede.objects.all().order_by("id"))
    fallback_sede = sedes[0] if sedes else None
    for sede in sedes:
        SedePolicy.objects.get_or_create(
            sede=sede,
            defaults={
                "max_equipos_aprendiz": 4,
                "guards_can_switch_sede": False,
                "qr_mode": "DUAL",
                "require_equipo_approval": True,
                "access_requires_active_turno": True,
            },
        )

    for user in Usuario.objects.all().iterator():
        role_code = str(getattr(user, "rol", "") or "").strip()
        role_obj = roles.get(role_code)
        if not role_obj:
            continue
        if role_code == "superadmin":
            target_sede = None
        else:
            target_sede = getattr(user, "sede_principal", None) or fallback_sede
            if not target_sede:
                continue
        membership, _ = UserMembership.objects.get_or_create(
            user=user,
            role=role_obj,
            sede=target_sede,
            defaults={"is_primary": True, "is_active": True, "can_switch_sede": False},
        )
        if not membership.is_primary:
            membership.is_primary = True
            membership.save(update_fields=["is_primary"])
        UserMembership.objects.filter(user=user).exclude(id=membership.id).update(is_primary=False)

    default_domains = {"sadi.test", "gmail.com", "outlook.com", "hotmail.com"}
    for role_code, role_obj in roles.items():
        role_domains = set(default_domains)
        for user in Usuario.objects.filter(rol=role_code).exclude(email__isnull=True).exclude(email=""):
            domain = _extract_domain(getattr(user, "email", ""))
            if domain:
                role_domains.add(domain)
        for domain in role_domains:
            AllowedEmailDomain.objects.get_or_create(
                role=role_obj,
                sede=None,
                domain=domain,
                defaults={"is_active": True},
            )


def noop_reverse(apps, schema_editor):
    # Keep seeded data for backward compatibility.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("accesos", "0013_refreshsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="SedePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_equipos_aprendiz", models.PositiveIntegerField(default=4)),
                ("guards_can_switch_sede", models.BooleanField(default=False)),
                (
                    "qr_mode",
                    models.CharField(
                        choices=[("PLAIN", "Plain"), ("SIGNED", "Signed"), ("DUAL", "Dual")],
                        default="DUAL",
                        max_length=10,
                    ),
                ),
                ("require_equipo_approval", models.BooleanField(default=True)),
                ("access_requires_active_turno", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sede",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="accesos.sede",
                    ),
                ),
            ],
            options={"ordering": ["sede__code"]},
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[("GLOBAL", "Global"), ("SEDE", "Sede"), ("OWN", "Propio")],
                        default="OWN",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accesos.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accesos.role",
                    ),
                ),
            ],
            options={"ordering": ["role__code", "permission__code", "scope"]},
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("can_switch_sede", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accesos.role",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accesos.sede",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accesos.usuario",
                    ),
                ),
            ],
            options={"ordering": ["-is_primary", "role__code", "sede__code"]},
        ),
        migrations.CreateModel(
            name="AllowedEmailDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_email_domains",
                        to="accesos.role",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_email_domains",
                        to="accesos.sede",
                    ),
                ),
            ],
            options={"ordering": ["role__code", "sede__code", "domain"]},
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(fields=("role", "permission", "scope"), name="uniq_role_permission_scope"),
        ),
        migrations.AddConstraint(
            model_name="usermembership",
            constraint=models.UniqueConstraint(fields=("user", "sede", "role"), name="uniq_membership_user_sede_role"),
        ),
        migrations.AddConstraint(
            model_name="usermembership",
            constraint=models.UniqueConstraint(
                condition=Q(is_primary=True),
                fields=("user", "role"),
                name="uniq_primary_membership_per_user_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="allowedemaildomain",
            constraint=models.UniqueConstraint(
                fields=("role", "sede", "domain"),
                name="uniq_allowed_domain_role_sede_domain",
            ),
        ),
        migrations.RunPython(seed_rbac_data, noop_reverse),
    ]
