# Generated by Django 6.0.2 on 2026-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0014_rbac_policies_and_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cierre_observacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
