# Generated by Django 6.0.2 on 2026-02-22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accesos", "0015_turno_cierre_observacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
                ),
                ("nombre_institucion", models.CharField(default="Institución", max_length=120)),
                (
                    "color_aprendiz_light",
                    models.CharField(
                        default="#14B8A6",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe estar en formato hexadecimal #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "color_aprendiz_dark",
                    models.CharField(
                        default="#0F766E",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe estar en formato hexadecimal #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "color_admin_light",
                    models.CharField(
                        default="#3B82F6",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe estar en formato hexadecimal #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "color_admin_dark",
                    models.CharField(
                        default="#1E3A8A",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe estar en formato hexadecimal #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "color_guarda_light",
                    models.CharField(
                        default="#F59E0B",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe estar en formato hexadecimal #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "color_guarda_dark",
                    models.CharField(
                        default="#B45309",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe estar en formato hexadecimal #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del sistema",
                "verbose_name_plural": "Configuración del sistema",
            },
        ),
    ]
