# Generated by Codex on 2026-03-21

from django.db import migrations


POSTGRES_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION accesos_enforce_membership_role_shape()
RETURNS trigger AS $$
DECLARE
    membership_role_code text;
BEGIN
    SELECT code INTO membership_role_code
    FROM accesos_role
    WHERE id = NEW.role_id;

    IF membership_role_code = 'superadmin' AND NEW.sede_id IS NOT NULL THEN
        RAISE EXCEPTION 'superadmin memberships must not have sede';
    END IF;

    IF membership_role_code IN ('admin_sede', 'guarda', 'aprendiz') AND NEW.sede_id IS NULL THEN
        RAISE EXCEPTION 'sede-scoped memberships must have sede';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

POSTGRES_CREATE_TRIGGER = """
CREATE TRIGGER accesos_membership_role_shape_trigger
BEFORE INSERT OR UPDATE OF role_id, sede_id
ON accesos_usermembership
FOR EACH ROW
EXECUTE FUNCTION accesos_enforce_membership_role_shape();
"""

POSTGRES_DROP_TRIGGER = """
DROP TRIGGER IF EXISTS accesos_membership_role_shape_trigger ON accesos_usermembership;
"""

POSTGRES_DROP_FUNCTION = """
DROP FUNCTION IF EXISTS accesos_enforce_membership_role_shape();
"""

SQLITE_CREATE_INSERT_TRIGGER = """
CREATE TRIGGER accesos_membership_role_shape_insert
BEFORE INSERT ON accesos_usermembership
FOR EACH ROW
BEGIN
    SELECT CASE
        WHEN (SELECT code FROM accesos_role WHERE id = NEW.role_id) = 'superadmin' AND NEW.sede_id IS NOT NULL
            THEN RAISE(ABORT, 'superadmin memberships must not have sede')
        WHEN (SELECT code FROM accesos_role WHERE id = NEW.role_id) IN ('admin_sede', 'guarda', 'aprendiz') AND NEW.sede_id IS NULL
            THEN RAISE(ABORT, 'sede-scoped memberships must have sede')
    END;
END;
"""

SQLITE_CREATE_UPDATE_TRIGGER = """
CREATE TRIGGER accesos_membership_role_shape_update
BEFORE UPDATE OF role_id, sede_id ON accesos_usermembership
FOR EACH ROW
BEGIN
    SELECT CASE
        WHEN (SELECT code FROM accesos_role WHERE id = NEW.role_id) = 'superadmin' AND NEW.sede_id IS NOT NULL
            THEN RAISE(ABORT, 'superadmin memberships must not have sede')
        WHEN (SELECT code FROM accesos_role WHERE id = NEW.role_id) IN ('admin_sede', 'guarda', 'aprendiz') AND NEW.sede_id IS NULL
            THEN RAISE(ABORT, 'sede-scoped memberships must have sede')
    END;
END;
"""

SQLITE_DROP_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS accesos_membership_role_shape_insert;"
SQLITE_DROP_UPDATE_TRIGGER = "DROP TRIGGER IF EXISTS accesos_membership_role_shape_update;"


def _merge_membership_flags(source, target):
    update_fields = []
    if source.is_primary and not target.is_primary:
        target.is_primary = True
        update_fields.append("is_primary")
    if source.is_active and not target.is_active:
        target.is_active = True
        update_fields.append("is_active")
    if source.can_switch_sede and not target.can_switch_sede:
        target.can_switch_sede = True
        update_fields.append("can_switch_sede")
    return update_fields


def _merge_duplicate_membership(source, *, role_id, sede_id, UserMembership):
    target = (
        UserMembership.objects.filter(
            user_id=source.user_id,
            role_id=role_id,
            sede_id=sede_id,
        )
        .exclude(pk=source.pk)
        .order_by("id")
        .first()
    )
    if target is None:
        return False
    update_fields = _merge_membership_flags(source, target)
    source.delete()
    if update_fields:
        target.save(update_fields=update_fields)
    return True


def normalize_membership_runtime_shapes(apps, schema_editor):
    Role = apps.get_model("accesos", "Role")
    UserMembership = apps.get_model("accesos", "UserMembership")

    superadmin_role, _ = Role.objects.get_or_create(
        code="superadmin",
        defaults={"name": "Superadmin", "is_system": True},
    )
    admin_sede_role, _ = Role.objects.get_or_create(
        code="admin_sede",
        defaults={"name": "Admin de sede", "is_system": True},
    )
    legacy_admin_role = Role.objects.filter(code="admin").first()

    if legacy_admin_role:
        for membership in UserMembership.objects.filter(role=legacy_admin_role).order_by("id"):
            if _merge_duplicate_membership(
                membership,
                role_id=admin_sede_role.id,
                sede_id=membership.sede_id,
                UserMembership=UserMembership,
            ):
                continue
            membership.role_id = admin_sede_role.id
            membership.save(update_fields=["role"])

    UserMembership.objects.filter(role=superadmin_role).exclude(sede__isnull=True).update(
        sede=None,
        can_switch_sede=True,
    )

    invalid_memberships = []
    sede_scoped_codes = {"admin_sede", "guarda", "aprendiz"}
    qs = (
        UserMembership.objects.filter(role__code__in=sede_scoped_codes, sede__isnull=True)
        .select_related("user", "role")
        .order_by("id")
    )
    for membership in qs:
        inferred_sede_id = getattr(membership.user, "sede_principal_id", None)
        if inferred_sede_id is None:
            sibling_sede_ids = list(
                UserMembership.objects.filter(user_id=membership.user_id, sede__isnull=False)
                .exclude(pk=membership.pk)
                .values_list("sede_id", flat=True)
                .distinct()
            )
            if len(sibling_sede_ids) == 1:
                inferred_sede_id = sibling_sede_ids[0]
        if inferred_sede_id is None:
            invalid_memberships.append(
                f"user={membership.user_id},membership={membership.pk},role={membership.role.code}"
            )
            continue
        if _merge_duplicate_membership(
            membership,
            role_id=membership.role_id,
            sede_id=inferred_sede_id,
            UserMembership=UserMembership,
        ):
            continue
        membership.sede_id = inferred_sede_id
        membership.save(update_fields=["sede"])

    if invalid_memberships:
        details = "; ".join(invalid_memberships)
        raise RuntimeError(f"Could not infer sede for legacy memberships during runtime shape hardening: {details}")


def create_membership_role_shape_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(POSTGRES_DROP_TRIGGER)
        schema_editor.execute(POSTGRES_TRIGGER_FUNCTION)
        schema_editor.execute(POSTGRES_CREATE_TRIGGER)
        return
    if vendor == "sqlite":
        schema_editor.execute(SQLITE_DROP_INSERT_TRIGGER)
        schema_editor.execute(SQLITE_DROP_UPDATE_TRIGGER)
        schema_editor.execute(SQLITE_CREATE_INSERT_TRIGGER)
        schema_editor.execute(SQLITE_CREATE_UPDATE_TRIGGER)


def drop_membership_role_shape_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(POSTGRES_DROP_TRIGGER)
        schema_editor.execute(POSTGRES_DROP_FUNCTION)
        return
    if vendor == "sqlite":
        schema_editor.execute(SQLITE_DROP_INSERT_TRIGGER)
        schema_editor.execute(SQLITE_DROP_UPDATE_TRIGGER)


class Migration(migrations.Migration):
    dependencies = [
        ("accesos", "0028_fix_access_guard_function_search_path"),
    ]

    operations = [
        migrations.RunPython(normalize_membership_runtime_shapes, migrations.RunPython.noop),
        migrations.RunPython(create_membership_role_shape_triggers, drop_membership_role_shape_triggers),
    ]
