# Generated by Codex on 2026-03-21

from django.db import migrations


SQLITE_DROP_VALIDATE_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS trg_validate_acceso_turno_insert_sqlite;"
SQLITE_DROP_VALIDATE_UPDATE_TRIGGER = "DROP TRIGGER IF EXISTS trg_validate_acceso_turno_update_sqlite;"
SQLITE_DROP_FILL_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS trg_fill_acceso_sede_from_turno_insert_sqlite;"
SQLITE_DROP_FILL_UPDATE_TRIGGER = "DROP TRIGGER IF EXISTS trg_fill_acceso_sede_from_turno_update_sqlite;"

SQLITE_VALIDATE_INSERT_TRIGGER = """
CREATE TRIGGER trg_validate_acceso_turno_insert_sqlite
BEFORE INSERT ON accesos_acceso
FOR EACH ROW
BEGIN
    SELECT CASE
        WHEN NEW.turno_id IS NULL THEN NULL
        WHEN NOT EXISTS (
            SELECT 1
            FROM accesos_turno
            WHERE id = NEW.turno_id
        ) THEN RAISE(ABORT, 'El turno asociado no existe.')
        WHEN EXISTS (
            SELECT 1
            FROM accesos_turno
            WHERE id = NEW.turno_id
              AND (activo IS NOT 1 OR fin IS NOT NULL)
        ) THEN RAISE(ABORT, 'El turno asociado no esta activo.')
        WHEN NEW.sede_id IS NOT NULL AND EXISTS (
            SELECT 1
            FROM accesos_turno
            WHERE id = NEW.turno_id
              AND sede_id <> NEW.sede_id
        ) THEN RAISE(ABORT, 'La sede del acceso debe coincidir con la sede del turno.')
    END;
END;
"""

SQLITE_VALIDATE_UPDATE_TRIGGER = """
CREATE TRIGGER trg_validate_acceso_turno_update_sqlite
BEFORE UPDATE OF turno_id, sede_id ON accesos_acceso
FOR EACH ROW
BEGIN
    SELECT CASE
        WHEN NEW.turno_id IS NULL THEN NULL
        WHEN NOT EXISTS (
            SELECT 1
            FROM accesos_turno
            WHERE id = NEW.turno_id
        ) THEN RAISE(ABORT, 'El turno asociado no existe.')
        WHEN EXISTS (
            SELECT 1
            FROM accesos_turno
            WHERE id = NEW.turno_id
              AND (activo IS NOT 1 OR fin IS NOT NULL)
        ) THEN RAISE(ABORT, 'El turno asociado no esta activo.')
        WHEN NEW.sede_id IS NOT NULL AND EXISTS (
            SELECT 1
            FROM accesos_turno
            WHERE id = NEW.turno_id
              AND sede_id <> NEW.sede_id
        ) THEN RAISE(ABORT, 'La sede del acceso debe coincidir con la sede del turno.')
    END;
END;
"""

SQLITE_FILL_INSERT_TRIGGER = """
CREATE TRIGGER trg_fill_acceso_sede_from_turno_insert_sqlite
AFTER INSERT ON accesos_acceso
FOR EACH ROW
WHEN NEW.turno_id IS NOT NULL AND NEW.sede_id IS NULL
BEGIN
    UPDATE accesos_acceso
       SET sede_id = (
           SELECT sede_id
             FROM accesos_turno
            WHERE id = NEW.turno_id
       )
     WHERE id = NEW.id;
END;
"""

SQLITE_FILL_UPDATE_TRIGGER = """
CREATE TRIGGER trg_fill_acceso_sede_from_turno_update_sqlite
AFTER UPDATE OF turno_id, sede_id ON accesos_acceso
FOR EACH ROW
WHEN NEW.turno_id IS NOT NULL AND NEW.sede_id IS NULL
BEGIN
    UPDATE accesos_acceso
       SET sede_id = (
           SELECT sede_id
             FROM accesos_turno
            WHERE id = NEW.turno_id
       )
     WHERE id = NEW.id;
END;
"""


def create_sqlite_access_invariant_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute(SQLITE_DROP_VALIDATE_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_DROP_VALIDATE_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_DROP_FILL_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_DROP_FILL_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_VALIDATE_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_VALIDATE_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_FILL_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_FILL_UPDATE_TRIGGER)


def drop_sqlite_access_invariant_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute(SQLITE_DROP_FILL_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_DROP_FILL_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_DROP_VALIDATE_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_DROP_VALIDATE_INSERT_TRIGGER)


class Migration(migrations.Migration):

    dependencies = [
        ("accesos", "0029_membership_runtime_shape_hardening"),
    ]

    operations = [
        migrations.RunPython(
            create_sqlite_access_invariant_triggers,
            reverse_code=drop_sqlite_access_invariant_triggers,
        ),
    ]
