# Generated by Codex on 2026-03-21

from django.db import migrations


SQLITE_DROP_EQUIPO_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS trg_check_max_equipos_insert_sqlite;"
SQLITE_DROP_EQUIPO_UPDATE_TRIGGER = "DROP TRIGGER IF EXISTS trg_check_max_equipos_update_sqlite;"

SQLITE_EQUIPO_INSERT_TRIGGER = """
CREATE TRIGGER trg_check_max_equipos_insert_sqlite
BEFORE INSERT ON accesos_equipo
FOR EACH ROW
WHEN NEW.propietario_id IS NOT NULL
BEGIN
    SELECT CASE
        WHEN (
            SELECT COUNT(*)
            FROM accesos_equipo
            WHERE propietario_id = NEW.propietario_id
        ) >= 4
        THEN RAISE(ABORT, 'No se pueden registrar mas de 4 equipos por aprendiz.')
    END;
END;
"""

SQLITE_EQUIPO_UPDATE_TRIGGER = """
CREATE TRIGGER trg_check_max_equipos_update_sqlite
BEFORE UPDATE OF propietario_id ON accesos_equipo
FOR EACH ROW
WHEN NEW.propietario_id IS NOT NULL AND NEW.propietario_id <> OLD.propietario_id
BEGIN
    SELECT CASE
        WHEN (
            SELECT COUNT(*)
            FROM accesos_equipo
            WHERE propietario_id = NEW.propietario_id
        ) >= 4
        THEN RAISE(ABORT, 'No se pueden registrar mas de 4 equipos por aprendiz.')
    END;
END;
"""


def create_sqlite_equipo_hard_cap_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute(SQLITE_DROP_EQUIPO_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_DROP_EQUIPO_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_EQUIPO_INSERT_TRIGGER)
    schema_editor.execute(SQLITE_EQUIPO_UPDATE_TRIGGER)


def drop_sqlite_equipo_hard_cap_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute(SQLITE_DROP_EQUIPO_UPDATE_TRIGGER)
    schema_editor.execute(SQLITE_DROP_EQUIPO_INSERT_TRIGGER)


class Migration(migrations.Migration):

    dependencies = [
        ("accesos", "0030_sqlite_access_invariant_triggers"),
    ]

    operations = [
        migrations.RunPython(
            create_sqlite_equipo_hard_cap_triggers,
            reverse_code=drop_sqlite_equipo_hard_cap_triggers,
        ),
    ]
